services:
  app:
    build: 
          context: ../../docker
          dockerfile: Dockerfile
    image: pbjh/minitwit-app:latest
    ports:
      - "8080:8080"
  api:
    build:
      context: ../../docker
      dockerfile: Dockerfile.api
    image: pbjh/minitwit-api:latest
    ports:
      - "8081:8081"