global:
  scrape_interval: 15s
  evaluation_interval: "15s"

# Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'minitwit-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']