FROM golang:1.23

WORKDIR /go/src/minitwit

COPY ../minitwit/go.mod ../minitwit/go.sum ./

RUN go mod download

COPY ../minitwit/ ./

WORKDIR /go/src/minitwit/api
RUN go build -o api

EXPOSE 8081

CMD ["./api"]