FROM golang:1.23

WORKDIR /go/src/minitwit

COPY ../minitwit/go.mod ../minitwit/go.sum ./

RUN go mod download

COPY ../minitwit/ ./

WORKDIR /api

RUN go build -o api

WORKDIR /go/src/minitwit/api

EXPOSE 8081

CMD ["./api"]