services:
  app:
    container_name: minitwit-app
    build:
          context: ../
          dockerfile: docker/Dockerfile
    image: pbjh/minitwit-app:latest
    ports:
      - "8080:8080"
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_DBNAME
      - DB_SSLMODE
      - DB_TIMEZONE
  api:
    container_name: minitwit-api
    build:
      context: ../
      dockerfile: docker/Dockerfile.api
    image: pbjh/minitwit-api:latest
    ports:
      - "8081:8081"
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
      - DB_DBNAME
      - DB_SSLMODE
      - DB_TIMEZONE

  prometheus:
    container_name: minitwit-prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - LOG_LEVEL=warn

  grafana:
    container_name: minitwit-grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_LOG_LEVEL=warn
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
