    name: Deploy services to DigitalOcean
    
    on:
      push:
        branches:
          - main
          - master
      workflow_dispatch: 
        
    jobs:
      linter:
        runs-on: ubuntu-latest
        environment: minitwit
        steps:
          - name: Hadolint Action
            uses: hadolint/hadolint-action@v3.1.0

      build-and-deploy:
        runs-on: ubuntu-latest
        environment: minitwit
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Verify secrets
            run: |
              echo "Checking if secrets are available:"
              echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
              echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"
              echo "SSH_USER is set: ${{ secrets.SSH_USER != '' }}"
              echo "SSH_HOST is set: ${{ secrets.SSH_HOST != '' }}"
              echo "ACTIONS_SSH_PRIVATE is set: ${{ secrets.ACTIONS_SSH_PRIVATE != '' }}"

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
    
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
    
          - name: Build and push minitwit-app
            uses: docker/build-push-action@v6
            with:
              context: .
              file: docker/Dockerfile
              push: true
              tags: pbjh/minitwit-app:latest
              cache-from: type=registry,ref=pbjh/minitwit-app:webbuildcache
              cache-to: type=registry,ref=pbjh/minitwit-app:webbuildcache,mode=max

          - name: Build and push minitwit-api
            uses: docker/build-push-action@v6
            with:
                context: .
                file: docker/Dockerfile.api
                push: true
                tags: pbjh/minitwit-api:latest
                cache-from: type=registry,ref=pbjh/minitwit-api:webbuildcache
                cache-to: type=registry,ref=pbjh/minitwit-api:webbuildcache,mode=max

          - name: Configure SSH
            run: |
              mkdir -p ~/.ssh/
              echo "${{ secrets.ACTIONS_SSH_PRIVATE }}" > ~/.ssh/do_ssh_key
              chmod 600 ~/.ssh/do_ssh_key
              ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            env:
              SSH_KEY: ${{ secrets.ACTIONS_SSH_PRIVATE }}
    
          - name: Deploy to server
            run: >
              ssh $SSH_USER@$SSH_HOST
              -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no
              '/minitwit/deploy.sh'
            env:
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_HOST: ${{ secrets.SSH_HOST }}
