name: Deploy services to DigitalOcean
    
on:
  push:
    branches:
      - main
      - master
      - fix-deployment
      - staging
  workflow_dispatch: 
    
jobs:
  #Calling reusable workflows
  call-hadolint:
    uses: Dev-ops-Gaming/MiniTwit/.github/workflows/docker-linter.yml@staging
  
  call-golangci:
    uses: Dev-ops-Gaming/MiniTwit/.github/workflows/golangci-lint.yml@staging

  run-tests:
    runs-on: ubuntu-latest
    needs: [call-hadolint, call-golangci]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Print repository structure and run_tests.sh content
        run: |
          echo "Project structure:"
          find . -type f -name "Dockerfile*" -o -name "docker-compose*" -o -name "run_tests.sh"
          
          echo "Content of run_tests.sh:"
          cat run_tests.sh

      - name: Create a custom test script
        run: |
          cat > run_minitwit_tests.sh << 'EOL'
          #!/bin/bash

          # Stop on first error
          set -e

          echo "Building and starting services..."

          # Clean up any existing containers
          echo "Cleaning up any existing containers..."
          docker-compose -f docker/docker-compose.test.yml down -v || true

          # Build the test container
          echo "Building test container..."
          docker build -t minitwit-uitests -f docker/Dockerfile.test .

          # Build the minitwit app
          echo "Building minitwit application..."
          docker build -t minitwit-app -f docker/Dockerfile .

          # Start PostgreSQL first
          echo "Starting PostgreSQL database..."
          docker-compose -f docker/docker-compose.test.yml up -d postgres
          echo "Waiting for PostgreSQL to be healthy..."
          sleep 15

          # Start minitwit
          echo "Starting MiniTwit application..."
          docker-compose -f docker/docker-compose.test.yml up -d minitwit

          # Wait for minitwit to become ready
          echo "Waiting for MiniTwit to initialize..."
          sleep 15

          # Check if MiniTwit container is running
          echo "Checking if MiniTwit container is running:"
          if ! docker ps | grep -q minitwit-app; then
              echo "ERROR: MiniTwit container is not running. Tests will not be executed."
              docker logs minitwit-app
              docker-compose -f docker/docker-compose.test.yml down -v
              exit 1
          fi

          # Run tests
          echo "Running UI and API tests..."
          docker-compose -f docker/docker-compose.test.yml up --abort-on-container-exit uitests

          # Get the exit code of the test container
          TEST_EXIT_CODE=$(docker inspect -f '{{.State.ExitCode}}' minitwit-uitests || echo "1")

          # Cleanup
          echo "Cleaning up containers and volumes..."
          docker-compose -f docker/docker-compose.test.yml down -v

          echo "Tests completed with exit code: $TEST_EXIT_CODE"
          exit $TEST_EXIT_CODE
          EOL
          
          chmod +x run_minitwit_tests.sh

      - name: Run Tests with Custom Script
        run: |
          sudo -E ./run_minitwit_tests.sh
        
  build-and-deploy:
    runs-on: ubuntu-latest
    # this job should run only if tests pass 
    needs: [run-tests]
    environment: minitwit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify secrets
        run: |
          echo "Checking if secrets are available:"
          echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"
          echo "SSH_USER is set: ${{ secrets.SSH_USER != '' }}"
          echo "SSH_HOST is set: ${{ secrets.SSH_HOST != '' }}"
          echo "ACTIONS_SSH_PRIVATE is set: ${{ secrets.ACTIONS_SSH_PRIVATE != '' }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push minitwit-app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: pbjh/minitwit-app:latest
          cache-from: type=registry,ref=pbjh/minitwit-app:webbuildcache
          cache-to: type=registry,ref=pbjh/minitwit-app:webbuildcache,mode=max

      - name: Build and push minitwit-api
        uses: docker/build-push-action@v6
        with:
            context: .
            file: docker/Dockerfile.api
            push: true
            tags: pbjh/minitwit-api:latest
            cache-from: type=registry,ref=pbjh/minitwit-api:webbuildcache
            cache-to: type=registry,ref=pbjh/minitwit-api:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.ACTIONS_SSH_PRIVATE }}" > ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.ACTIONS_SSH_PRIVATE }}

      - name: Sync files with rsync
        run: |
         rsync -avz --delete \
            -e "ssh -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no" \
            ./remote_files/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/minitwit/

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '/minitwit/deploy.sh'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}