name: Deploy services to DigitalOcean
    
on:
  push:
    branches:
      - main
      - master
      - fix-deployment
  workflow_dispatch: 
    
jobs:
  #Calling reusable workflows
  call-hadolint:
    uses: Dev-ops-Gaming/MiniTwit/.github/workflows/docker-linter.yml@staging
  
  call-golangci:
    uses: Dev-ops-Gaming/MiniTwit/.github/workflows/golangci-lint.yml@staging

  run-tests:
    runs-on: ubuntu-latest
    needs: [call-hadolint, call-golangci]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'  # Specify the Go version you're using

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Find run_tests.sh script
        id: find_test_script
        run: |
          SCRIPT_PATH=$(find . -name "run_tests.sh" -type f | head -n 1)
          if [ -z "$SCRIPT_PATH" ]; then
            echo "Error: run_tests.sh script not found in the repository"
            exit 1
          fi
          echo "SCRIPT_PATH=${SCRIPT_PATH}" >> $GITHUB_OUTPUT
          echo "Found test script at: ${SCRIPT_PATH}"

      - name: Run Test Suite
        run: |
          cd $(dirname "${{ steps.find_test_script.outputs.SCRIPT_PATH }}")
          echo "Running tests from directory: $(pwd)"
          sudo chmod +x ./run_tests.sh
          # Run tests and capture output
          sudo ./run_tests.sh 
          # Explicitly check exit code and fail if non-zero
          if [ $? -ne 0 ]; then
            echo "Tests failed! Aborting deployment."
            exit 1
          fi
        
  build-and-deploy:
    runs-on: ubuntu-latest
    # this job should run only if tests pass 
    needs: [run-tests]
    environment: minitwit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify secrets
        run: |
          echo "Checking if secrets are available:"
          echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"
          echo "SSH_USER is set: ${{ secrets.SSH_USER != '' }}"
          echo "SSH_HOST is set: ${{ secrets.SSH_HOST != '' }}"
          echo "ACTIONS_SSH_PRIVATE is set: ${{ secrets.ACTIONS_SSH_PRIVATE != '' }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push minitwit-app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: pbjh/minitwit-app:latest
          cache-from: type=registry,ref=pbjh/minitwit-app:webbuildcache
          cache-to: type=registry,ref=pbjh/minitwit-app:webbuildcache,mode=max

      - name: Build and push minitwit-api
        uses: docker/build-push-action@v6
        with:
            context: .
            file: docker/Dockerfile.api
            push: true
            tags: pbjh/minitwit-api:latest
            cache-from: type=registry,ref=pbjh/minitwit-api:webbuildcache
            cache-to: type=registry,ref=pbjh/minitwit-api:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          printf "%s\n" "${{ secrets.ACTIONS_SSH_PRIVATE }}" > ~/.ssh/do_ssh_key
          chmod 600 ~/.ssh/do_ssh_key
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        env:
          SSH_KEY: ${{ secrets.ACTIONS_SSH_PRIVATE }}

      - name: Sync files with rsync
        run: |
         rsync -avz --delete \
            -e "ssh -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no" \
            ./remote_files/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/minitwit/

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/do_ssh_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '/minitwit/deploy.sh'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}