    name: Use Hadolint on dockerfiles
    
    on:
      push:
        branches:
          - enhancement/static_analysis_tools
      workflow_dispatch: 
        
    jobs:
      linter:
        runs-on: ubuntu-latest
        environment: minitwit
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Hadolint Action app
            uses: hadolint/hadolint-action@v3.1.0
            id: app
            with: 
              dockerfile: docker/Dockerfile

          - name: Update Pull Request
            uses: actions/github-script@v6
            if: github.event_name == 'pull_request'
            with:
              script: |
                const output = `
                #### Hadolint: \`${{ steps.app.outcome }}\`
                \`\`\`
                ${process.env.HADOLINT_RESULTS}
                \`\`\`
                `;

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })

          - name: Hadolint Action api
            uses: hadolint/hadolint-action@v3.1.0
            id: api
            with: 
              dockerfile: docker/Dockerfile.api

          - name: Update Pull Request
            uses: actions/github-script@v6
            if: github.event_name == 'pull_request'
            with:
              script: |
                const output = `
                #### Hadolint: \`${{ steps.api.outcome }}\`
                \`\`\`
                ${process.env.HADOLINT_RESULTS}
                \`\`\`
                `;

                github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: output
                })