    name: Use Hadolint on dockerfiles
    
    on:
      push:
        branches:
          - enhancement/static_analysis_tools
      workflow_dispatch: 
        
    jobs:
      hadolint:
        runs-on: ubuntu-latest
        environment: minitwit
        steps:
          - name: Checkout
            uses: actions/checkout@v2

          - name: Hadolint Action app
            uses: hadolint/hadolint-action@v3.1.0
            with: 
              dockerfile: docker/Dockerfile

          - name: Hadolint Action api
            uses: hadolint/hadolint-action@v3.1.0
            with: 
              dockerfile: docker/Dockerfile.api