    name: Run static tools for staging
    
    on:
      push:
        branches:
          - staging
      workflow_dispatch: 
        
    jobs:
      #Calling reusable workflows
      call-hadolint:
        uses: Dev-ops-Gaming/MiniTwit/.github/workflows/docker-linter.yml@staging
      
      call-golangci:
        uses: Dev-ops-Gaming/MiniTwit/.github/workflows/golangci-lint.yml@staging
