    name: Test reusable workflow

    on:
      push:
        branches:
          - enhancement/static_analysis_tools
      workflow_dispatch:

    jobs:
      call-hadolint:
        uses: Dev-ops-Gaming/MiniTwit/.github/workflows/docker-linter.yml@enhancement/static_analysis_tools
